name: push-windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: ${{ matrix.config.name }} ${{ matrix.qt-version }} ${{ matrix.config.arch }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - name: "Windows latest"
          os: windows-latest
          install-qt-arch: 'win64_msvc2019_64'
          msvc_arch: x64
        qt-version: ['5.15.2']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ matrix.qt-version }}
        install-deps: 'true'
        host: windows
        target: desktop
        arch: ${{ matrix.config.install-qt-arch }}
        dir: ${{ github.workspace }}

    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: ${{ matrix.config.msvc_arch }}

    - name: Versions
      shell: cmd
      run: |
        qmake -v
        qmake -query QMAKE_SPEC

    - name: Build
      shell: cmd
      run: |
        cd sources
        qmake -r CONFIG+=debug ./OpenHXServer.pro
        nmake
        cd ..
